name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  golangci:
    strategy:
      matrix:
        go: [1.18]
        os: [ubuntu-latest, macos-latest]
    name: Tests
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: 'latest'

      - name: Golang-ci install
        if: runner.os == 'Linux'
        run: make lintci-deps

      - name: Lint
        if: runner.os == 'Linux'
        run: make lint

      - name: Test
        if: runner.os == 'Linux'
        run: make tests
